### ISSUE TITLE
this prooject can`t use the 'yarn install' directive 

### ISSUE THREAD

**Issue by ZooTopiaGG** [joeldenning/simple-single-spa-webpack-example#18]
but can be used npm run install

**Comment by internettrans** [comment]
Not sure what you mean by `yarn install` directive? Are you referring to just running `yarn install`? Are you seeing an error with that?

**Comment by pringelmann** [comment]
Not sure if this is related to the OP's issue but I am getting the following when running `npm install` immediately after cloning:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ecstatic@^2.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'http-server'
npm ERR! notarget
```

**Comment by internettrans** [comment]
Use `yarn install`, as instructed in the readme. That way definitely works for me right now (just tried it twice).
