### ISSUE TITLE
Problem executing the example

### ISSUE THREAD

**Issue by paulolvilar** [joeldenning/simple-single-spa-webpack-example#19]
hi there,

got this error when i click the app2 link

Chromium:
Unhandled Promise rejection: props is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: props is not defined
    at single-spa-angular.js:60
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at zone.js:889
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601) ReferenceError: props is not defined
    at http://localhost:8080/dist/common-dependencies.js.js:88280:56
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:8080/dist/common-dependencies.js.js:89228:26)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:8080/dist/common-dependencies.js.js:88987:43)
    at http://localhost:8080/dist/common-dependencies.js.js:89726:34
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8080/dist/common-dependencies.js.js:89260:31)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:8080/dist/common-dependencies.js.js:89032:47)
    at drainMicroTaskQueue (http://localhost:8080/dist/common-dependencies.js.js:89438:35)
api.onUnhandledError @ zone.js:682
handleUnhandledRejection @ zone.js:709
_loop_1 @ zone.js:699
api.microtaskDrainDone @ zone.js:703
drainMicroTaskQueue @ zone.js:608
Promise.then (async)
scheduleMicroTask @ zone.js:584
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:258
scheduleResolveOrReject @ zone.js:879
ZoneAwarePromise.then @ zone.js:1012
bootstrap @ single-spa-angular.js:58
bootstrap @ app2.js:19
i @ single-spa.js:1
(anonymous) @ single-spa.js:1
ZoneAwarePromise @ zone.js:910
(anonymous) @ single-spa.js:1
(anonymous) @ single-spa.js:1
r @ single-spa.js:1
(anonymous) @ single-spa.js:1
t.(anonymous function) @ single-spa.js:1
r @ single-spa.js:1
(anonymous) @ single-spa.js:1
e @ single-spa.js:1
(anonymous) @ single-spa.js:1
(anonymous) @ single-spa.js:1
Promise.then (async)
(anonymous) @ single-spa.js:1
(anonymous) @ single-spa.js:1
r @ single-spa.js:1
(anonymous) @ single-spa.js:1
t.(anonymous function) @ single-spa.js:1
r @ single-spa.js:1
(anonymous) @ single-spa.js:1
e @ single-spa.js:1
(anonymous) @ single-spa.js:1
(anonymous) @ single-spa.js:1
o @ single-spa.js:1
window.history.pushState @ single-spa.js:1
r @ single-spa.js:1
onclick @ (index):59
single-spa-angular.js:60 Uncaught ReferenceError: props is not defined
    at single-spa-angular.js:60
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at zone.js:889
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
(anonymous) @ single-spa-angular.js:60
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
(anonymous) @ zone.js:889
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
setTimeout (async)
scheduleTask @ zone.js:2302
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:261
scheduleMacroTaskWithCurrentZone @ zone.js:1245
(anonymous) @ zone.js:2317
proto.(anonymous function) @ zone.js:1569
r @ single-spa.js:1
(anonymous) @ single-spa.js:1
r @ single-spa.js:1
(anonymous) @ single-spa.js:1
t.(anonymous function) @ single-spa.js:1
r @ single-spa.js:1
(anonymous) @ single-spa.js:1
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
(anonymous) @ zone.js:889
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
Promise.then (async)
scheduleMicroTask @ zone.js:584
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:258
scheduleResolveOrReject @ zone.js:879
resolvePromise @ zone.js:825
(anonymous) @ zone.js:741
Promise.then (async)
(anonymous) @ zone.js:1092
ZoneAwarePromise @ zone.js:910
Ctor.then @ zone.js:1091
r @ single-spa.js:1
(anonymous) @ single-spa.js:1
e @ single-spa.js:1
(anonymous) @ single-spa.js:1
(anonymous) @ single-spa.js:1
Promise.then (async)
(anonymous) @ single-spa.js:1
(anonymous) @ single-spa.js:1
r @ single-spa.js:1
(anonymous) @ single-spa.js:1
t.(anonymous function) @ single-spa.js:1
r @ single-spa.js:1
(anonymous) @ single-spa.js:1
e @ single-spa.js:1
(anonymous) @ single-spa.js:1
(anonymous) @ single-spa.js:1
o @ single-spa.js:1
window.history.pushState @ single-spa.js:1
r @ single-spa.js:1
onclick @ (index):59

Firefox:
ReferenceError: props is not defined[Learn More]  common-dependencies.js.js:88280:5
	bootstrap/< http://localhost:8080/dist/common-dependencies.js.js:88280:5
	["./node_modules/zone.js/dist/zone.js"]/</</ZoneDelegate.prototype.invoke http://localhost:8080/dist/common-dependencies.js.js:89228:17
	["./node_modules/zone.js/dist/zone.js"]/</</Zone.prototype.run http://localhost:8080/dist/common-dependencies.js.js:88987:24
	scheduleResolveOrReject/< http://localhost:8080/dist/common-dependencies.js.js:89726:29
	["./node_modules/zone.js/dist/zone.js"]/</</ZoneDelegate.prototype.invokeTask http://localhost:8080/dist/common-dependencies.js.js:89260:17
	["./node_modules/zone.js/dist/zone.js"]/</</Zone.prototype.runTask http://localhost:8080/dist/common-dependencies.js.js:89032:28
	drainMicroTaskQueue http://localhost:8080/dist/common-dependencies.js.js:89438:25
	["./node_modules/core-js/client/shim.min.js"]/</</R/</n http://localhost:8080/dist/common-dependencies.js:58530:3508
	["./node_modules/core-js/client/shim.min.js"]/</</R/< http://localhost:8080/dist/common-dependencies.js:58530:3653
	["./node_modules/core-js/client/shim.min.js"]/</</t.exports/t http://localhost:8080/dist/common-dependencies.js:58528:27620

**Comment by internettrans** [comment]
If what you're looking for is angular microfrontends check out this working repo: https://github.com/joeldenning/coexisting-angular-microfrontends.

Once single-spa-angular@beta is released, I will update this repo to use it. However, right this repo isn't using angular-cli or single-spa-angular@3, which is the future of single-spa + angular support.

I'm closing this issue, in favor of encouraging you and others to use single-spa-angular@>=3 (currently beta)
