### ISSUE TITLE
Why not dependencies in externals of webpack

### ISSUE THREAD

**Issue by Flamingo09** [joeldenning/simple-single-spa-webpack-example#36]
By going through webpack config, I understand that you are optimizing dependencies by applying split chunks on it. If you don't mention those dependencies in external, won't they be re-fetched for each micro-app and also, why adding them in entry point.

Just trying to understand the purpose of the code, the way it is written.

**Comment by internettrans** [comment]
Hi @Flamingo09, good question.

When everything is in a single repo with a single webpack config, webpack can do all the optimizations to avoid duplicate dependencies without marking things as externals.

**Comment by Flamingo09** [comment]
Thanks 👍
