### ISSUE TITLE
Compilation issue due to missing angular module

### ISSUE THREAD

**Issue by tsukhu** [joeldenning/simple-single-spa-webpack-example#4]
@angular/platform-browser-dynamic is missing from the package.json

ERROR in ./src/app2/app2.js
Module not found: Error: Can't resolve '@angular/platform-browser-dynamic' in 'E:\workspace\simple-single-spa-webpack-example\src\app2'
 @ ./src/app2/app2.js 18:30-74
 @ ./src/root-application/root-application.js

**Comment by internettrans** [comment]
Apologies for the extremely late response -- is this still an issue?

Closing for now but feel free to reopen with further questions or discussion
